### ISSUE TITLE
How to install this?

### ISSUE THREAD

**Issue by jgrn307** [geomatik/qlsu#1]
Hi there, we're interested in trying this plugin out but how should it be installed?  Do you have tutorials/demos for it?

**Comment by geomatik** [comment]
Hello @jgrn307 

In order to install the QLSU plugin, you can either download the repository as zip file or clone using git and create a zip file. The plugin works with QGIS 3.x versions. Then using the `Plugins>Manage and Install Plugins` menu of QGIS, you can install QLSU plugin by selecting the "Install from ZIP" option from `Manage and Install Plugins` dialog. The plugin will locate itself under the Raster menu. I do not have tutorials and a full documentation yet but they will be added soon.

However the technical implementation and theoretical framework of the plugin is presented in the following paper;

- Celik, B. (2023). QLSU (QGIS Linear Spectral Unmixing) Plugin: An open source linear spectral unmixing tool for hyperspectral & multispectral remote sensing imagery. Environmental Modelling & Software, 168, 105782. https://www.sciencedirect.com/science/article/abs/pii/S1364815223001688
